@HealthCheck.Server_HostAddress = https://localhost:40443

GET {{HealthCheck.Server_HostAddress}}/api/broadcast/Update

###

GET {{HealthCheck.Server_HostAddress}}/api/broadcast/update2

###

HEAD {{HealthCheck.Server_HostAddress}}/api/heartbeat

###

GET {{HealthCheck.Server_HostAddress}}/Error

###
